### ISSUE TITLE
`NestedFrame.query(None)` should return an explicit error

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/nested-pandas#114]
Providing no input to query should return an explicit value error

**Comment by dougbrn** [comment]
The line `df.query(None)`:
Nested-Pandas returns `TypeError: object of type 'NoneType' has no len()`
Wheras Pandas returns an explicit error: `ValueError: expr must be a string to be evaluated, <class 'NoneType'> given`

**Comment by harsha-mangena** [comment]
@dougbrn, Can I pick this issue?

**Comment by gitosaurus** [comment]
Resolved as part of #150 .  Now `NestedFrame.query` produces the identical error to `DataFrame.query` for the same edge conditions.
