### ISSUE TITLE
MVP: Implement a batch/apply style function

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/nested-pandas#14]
**Feature request**
Blocks #9. We want to apply a function, such as a periodogram function, to all lightcurves stored within a nested structure. We should implement a simple function for applying this function to the lightcurves. With TAPE, this motivated the batch function for grouping the sources and applying a function to them. Our data structures motivate a custom function a bit less, as the data is pre-grouped. So using the base apply may potentially be fine, however we may be able to provide a more intuitive API function for doing this operation and can potentially optimize for how it accesses the lightcurve data under the hood. Usage should look something like this:

```
mean_flux = nf.batch(my_mean_flux, "my_nested.flux")
```

**Before submitting**
Please check the following:

- [x] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [x] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [x] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by wilsonbb** [comment]
A small suggestion here is that I would avoid the name "batch" here since it has the connotation that we're doing batch processing of splitting the job into multiple computable batches. That connotation makes less sense here where there is no applied parallelism.
