### ISSUE TITLE
Cross-nest queries in NestedFrame.query should be prohibited or split

### ISSUE THREAD

**Issue by gitosaurus** [lincc-frameworks/nested-pandas#160]
**Bug report**

**Before submitting**
Please check the following:

- [X] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [X] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a description of what I expected instead.
- [X] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

Processing queries across base and nested columns is not possible in `NestedFrame.query` today, so expressions of this kind are detected and prohibited.  However, it does not presently prohibit queries that go across two different nests:

```python
nf.query("n1.c < 0.5 and n2.d > 1e-7")
```

The above will "work", but only selects the nested rows in `n1`, simply because `n1` is earlier in the string.

The solution is to treat such cross-nest queries exactly the same as queries that cross base and nested columns: error out today, and as split queries, in the future.

**Comment by hombit** [comment]
I'd raise an error for such queries, at least until we have a more complete implementation
