### ISSUE TITLE
Fix NestedFrame.query/eval to handle column names including a space

### ISSUE THREAD

**Issue by wilsonbb** [lincc-frameworks/nested-pandas#174]
We recently introduced an AST parser for evaluation of expressions against Nested-Pandas columns in `eval` and `query`.

However this seems to fail against column names which include a space (which is allowed in base Pandas).

This was discovered when updating the `nested-dask` version for `lsdb` since one of their unit tests exercises a query against such a column. Here is the example test failure with a full stack trace when our current query/eval parser is used by LSDB: https://github.com/astronomy-commons/lsdb/actions/runs/11713280862/job/32625751711?pr=493

A pretty trivial reproduction:

```
from nested_pandas import NestedFrame
import pandas as pd

nf = NestedFrame(data={"dog": [1, 2, 3], "good dog": [2, 4, 6]}, index=[0, 1, 2])

nested = pd.DataFrame(
    data={"a": [0, 2, 4, 1, 4, 3, 1, 4, 1], "b": [5, 4, 7, 5, 3, 1, 9, 3, 4]},
    index=[0, 0, 0, 1, 1, 1, 2, 2, 2],
)

nf = nf.add_nested(nested, "nested")
nf.query("`good dog` > 3")
```

**Comment by gitosaurus** [comment]
The problem arises in `extract_nest_names`, a new function which calls `ast.parse` directly, but which needs to go through the Pandas preprocessing of AST parse trees in order to handle this types of column names.  The fix will be to call the Pandas evaluator to get the *modified* parse tree before extracting nest names.

**Comment by gitosaurus** [comment]
> The problem arises in `extract_nest_names`, a new function which calls `ast.parse` directly, but which needs to go through the Pandas preprocessing of AST parse trees in order to handle this types of column names. The fix will be to call the Pandas evaluator to get the _modified_ parse tree before extracting nest names.

The branch has been updated to solve the problem of non-identifier names for base, un-nested columns.  The solution doesn't work yet with non-identifier names for nested columns (not the fields, but the upper name itself).  The problem appears to be related to the Pandas expression engine rewriting backtick-enclosed fields and using a separate resolver for them.
