### ISSUE TITLE
`reduce` fails with duplicate column names

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/nested-pandas#35]
**Bug report**
`reduce` cannot handle duplicate column names in multiple nested dataframes, as it "flattens" all the input columns to a single dataframe. Fixing this should wait until #33 is resolved. Knowingly introduced by #34 .

**Before submitting**
Please check the following:

- [ ] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [ ] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by wilsonbb** [comment]
One potential solution here is to rename the columns when generating the merged frame to the form `layer.column`. Then before returning the result frame we rename all of the columns to drop the `layer.` prefix. 

Renaming columns should in theory be cheap here

**Comment by dougbrn** [comment]
I don't think this is mission-critical for v0.1 so I'm opting to remove it from the milestone for now
