### ISSUE TITLE
Frame-level interface to get and set nested columns

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/nested-pandas#99]
**Feature request**

It would be great to support code like this:

```python
time = nested_frame["nested.time"]
nested_frame["nested.time"] = time - 58000
nested_frame["nested.passband"] = "lsst_" + nested_frame["nested.band"]
```

**Before submitting**
Please check the following:

- [x] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [x] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [ ] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by dougbrn** [comment]
+1 to priority, we ran into this when working with the IRSA demo notebook and our solution is worse than base pandas. E.g. they wanted to do this:

```
#reset zero time to be start of that mission
band_lc["time"] = band_lc["time"] - band_lc["time"].min()
```

And the best we could do was to basically build a whole new nestedframe with this (and repack from lists)

```
mintime = band_lc.lc.nest.to_flat().time.min()

def retime(time, flux, err, band, label, mintime):
    return {"time":time-mintime, "flux":flux, "err":err, "band":band, "label": label}


res = npd.series.packer.pack_lists(band_lc.reduce(retime, "lc.time", "lc.flux", "lc.err", "lc.band", "lc.label", mintime)).to_frame().rename(columns={0:"lc"})
```
